environment:
  matrix:
    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    - PYTHON: "C:\\Python27"
      TOXENV: "py27"
    - PYTHON: "C:\\Python33"
      TOXENV: "py33"
    - PYTHON: "C:\\Python34"
      TOXENV: "py34"
    - PYTHON: "C:\\Python35"
      TOXENV: "py35"
    - PYTHON: "C:\\Python36"
      TOXENV: "py36"

install:
  - pip install tox
  - choco install python.pypy
  - set PATH=C:\tools\pypy\pypy;%PATH% # so tox can find pypy

build: off

test_script:
  - tox -e %TOXENV%
